DECLARE
    TABLESPACE_EXISTS EXCEPTION;
    USER_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(TABLESPACE_EXISTS, -01543);
    PRAGMA EXCEPTION_INIT(USER_EXISTS, -01920);

    PROCEDURE RUN(query VARCHAR2) AS
    BEGIN
        EXECUTE IMMEDIATE query;
    EXCEPTION WHEN TABLESPACE_EXISTS OR USER_EXISTS THEN NULL;
    END;
BEGIN
    RUN('CREATE TABLESPACE USER_DATA DATAFILE ''/opt/oracle/oradata/XE/USER_DATA.dbf'' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED');
    RUN('CREATE USER APP_USER IDENTIFIED BY APP_PASS DEFAULT TABLESPACE USER_DATA');
END;

GRANT CONNECT, RESOURCE, CREATE SESSION TO APP_USER;
GRANT CREATE TABLE, CREATE VIEW TO APP_USER;
GRANT UNLIMITED TABLESPACE TO APP_USER;
