DECLARE
    TABLE_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(TABLE_NOT_EXISTS, -00942);

    PROCEDURE RUN(query VARCHAR2) AS
    BEGIN
        EXECUTE IMMEDIATE query;
    EXCEPTION WHEN TABLE_NOT_EXISTS THEN NULL;
    END;
BEGIN
    RUN('DROP TABLE TEST_SOURCE');
    RUN('DROP TABLE TEST_SINK');
EXCEPTION WHEN TABLE_NOT_EXISTS THEN NULL;
END;

TRUNCATE TABLE ETL_MAPPINGS;

CREATE TABLE TEST_SOURCE (
    RUNNING_ID NUMBER,
    ROW_DATE   DATE DEFAULT SYSDATE,
    FIELD_A    VARCHAR2(50),
    FIELD_B    VARCHAR2(50),
    FIELD_C    VARCHAR2(50),
    CONSTRAINT PK_TEST_SOURCE PRIMARY KEY (RUNNING_ID)
);

CREATE TABLE TEST_SINK (
    RUNNING_ID NUMBER,
    ROW_DATE   DATE DEFAULT SYSDATE,
    FIELD_A    VARCHAR2(50),
    FIELD_B    VARCHAR2(50),
    FIELD_C    VARCHAR2(50),
    CONSTRAINT PK_TEST_SINK PRIMARY KEY (RUNNING_ID)
);

CREATE OR REPLACE VIEW V_TEST_SOURCE AS
SELECT RUNNING_ID, ROW_DATE, FIELD_A, FIELD_B, FIELD_C FROM TEST_SOURCE;

MERGE INTO TEST_SOURCE A
USING (
    SELECT 1 AS RUNNING_ID, TO_DATE('2025-01-01', 'YYYY-MM-DD') AS ROW_DATE, 'A1' AS FIELD_A, 'B1' AS FIELD_B, 'C1' AS FIELD_C FROM DUAL UNION ALL
    SELECT 2, TO_DATE('2025-01-02', 'YYYY-MM-DD'), 'A2', 'B2', 'C2' FROM DUAL UNION ALL
    SELECT 3, TO_DATE('2025-01-03', 'YYYY-MM-DD'), 'A3', 'B3', 'C3' FROM DUAL UNION ALL
    SELECT 4, TO_DATE('2025-01-04', 'YYYY-MM-DD'), 'A4', 'B4', 'C4' FROM DUAL UNION ALL
    SELECT 5, TO_DATE('2025-01-05', 'YYYY-MM-DD'), 'A5', 'B5', 'C5' FROM DUAL
) B
ON (A.RUNNING_ID = B.RUNNING_ID)
WHEN MATCHED THEN
UPDATE SET
    A.ROW_DATE = B.ROW_DATE,
    A.FIELD_A = B.FIELD_A,
    A.FIELD_B = B.FIELD_B,
    A.FIELD_C = B.FIELD_C
WHEN NOT MATCHED THEN
INSERT (RUNNING_ID, ROW_DATE, FIELD_A, FIELD_B, FIELD_C)
VALUES (B.RUNNING_ID, B.ROW_DATE, B.FIELD_A, B.FIELD_B, B.FIELD_C);

INSERT INTO ETL_MAPPINGS (SRC_OBJ, DST_OBJ) VALUES ('V_TEST_SOURCE', 'TEST_SINK');
PURGE RECYCLEBIN;
